"""
PDF report generator for Veritas.

Layout is intentionally minimal — swap in Figma-designed branding
by updating the header/footer and adding logo assets.
"""

import io

from fpdf import FPDF

from models import AnalysisResult


def _safe(text: str) -> str:
    """Replace Unicode characters unsupported by Helvetica with ASCII equivalents."""
    return text.replace("\u2013", "-").replace("\u2014", "--").replace("\u2019", "'")


class VeritasReport(FPDF):
    # ── placeholder branding — replace with Figma assets ──

    def header(self):
        self.set_font("Helvetica", "B", 22)
        self.cell(0, 12, "VERITAS", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(100, 100, 100)
        self.cell(
            0, 5, "AI Voice Authentication Platform",
            align="C", new_x="LMARGIN", new_y="NEXT",
        )
        self.set_text_color(0, 0, 0)
        y = self.get_y() + 3
        self.line(10, y, 200, y)
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}  |  Generated by Veritas", align="C")


def _label_value(pdf: FPDF, label: str, value: str):
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(45, 7, f"{label}:")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 7, value, new_x="LMARGIN", new_y="NEXT")


def generate_pdf(
    report_id: str,
    analysis: AnalysisResult,
    heatmap_png: bytes | None = None,
) -> bytes:
    pdf = VeritasReport()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── metadata ──
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Analysis Report", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    for label, value in [
        ("Report ID", report_id),
        ("Audio File ID", analysis.file_id),
        ("Filename", analysis.filename),
        ("Analysis Date", analysis.analyzed_at),
        ("Model", analysis.model_used),
    ]:
        _label_value(pdf, label, value)
    pdf.ln(4)

    # ── verdict ──
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Verdict", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "B", 18)
    if analysis.overall_score >= 50:
        pdf.set_text_color(180, 30, 30)
    else:
        pdf.set_text_color(30, 130, 50)
    pdf.cell(0, 12, analysis.verdict, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"AI Probability: {analysis.overall_score:.1f}%", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(
        0, 8,
        f"Confidence Interval: {analysis.confidence_low:.1f}% - {analysis.confidence_high:.1f}%",
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.ln(4)

    # ── heatmap ──
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Confidence Heatmap", new_x="LMARGIN", new_y="NEXT")

    if heatmap_png:
        pdf.image(io.BytesIO(heatmap_png), x=10, w=190)
        pdf.ln(4)
    else:
        y = pdf.get_y()
        pdf.set_fill_color(245, 245, 245)
        pdf.rect(10, y, 190, 30, "F")
        pdf.set_draw_color(200, 200, 200)
        pdf.rect(10, y, 190, 30, "D")
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(150, 150, 150)
        pdf.set_xy(10, y + 10)
        pdf.cell(190, 10, "[Heatmap visualization -- placeholder]", align="C")
        pdf.set_text_color(0, 0, 0)
        pdf.set_y(y + 35)

    # ── summary ──
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, _safe(analysis.summary))
    pdf.ln(4)

    # ── segment table ──
    if analysis.segments:
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Segment Analysis", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "B", 9)
        pdf.set_fill_color(139, 26, 26)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(35, 7, "Time Range", border=1, fill=True)
        pdf.cell(25, 7, "Score", border=1, fill=True)
        pdf.cell(130, 7, "Key Contributors", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)

        pdf.set_font("Helvetica", "", 9)
        for i, seg in enumerate(analysis.segments):
            if i % 2 == 0:
                pdf.set_fill_color(250, 250, 250)
            fill = i % 2 == 0
            pdf.cell(35, 7, f"{seg.start_time:.1f}s - {seg.end_time:.1f}s", border=1, fill=fill)
            pdf.cell(25, 7, f"{seg.confidence_score:.1f}%", border=1, fill=fill)
            pdf.cell(
                130, 7, ", ".join(seg.contributors[:3]),
                border=1, fill=fill, new_x="LMARGIN", new_y="NEXT",
            )

    # ── speaker match ──
    if analysis.speaker_match:
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Speaker Identity Match", new_x="LMARGIN", new_y="NEXT")
        sm = analysis.speaker_match
        _label_value(pdf, "Claimed Speaker", sm.claimed_speaker)
        _label_value(pdf, "Similarity", f"{sm.similarity_score:.1f}%")
        _label_value(pdf, "Interpretation", _safe(sm.interpretation))

    return bytes(pdf.output())
