import os

from fpdf import FPDF

from models import AnalysisResult

REPORTS_DIR = "/tmp/veritas/reports"
os.makedirs(REPORTS_DIR, exist_ok=True)

DARK_RED = (139, 26, 26)
GREEN = (27, 130, 50)
FALSE_RED = (192, 57, 43)
MISLEADING_ORANGE = (211, 84, 0)
GRAY = (100, 100, 100)


def _safe(text: str) -> str:
    text = (
        text.replace("\u2013", "-")
            .replace("\u2014", "--")
            .replace("\u2019", "'")
            .replace("\u2018", "'")
            .replace("\u201c", '"')
            .replace("\u201d", '"')
            .replace("\u2026", "...")
            .replace("\u00b7", "-")
            .replace("\u2022", "-")
    )
    # Strip any remaining characters outside Latin-1 that Helvetica can't render
    return text.encode("latin-1", errors="replace").decode("latin-1")


class VeritasReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 22)
        self.set_text_color(*DARK_RED)
        self.cell(0, 12, "VERITAS", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*GRAY)
        self.cell(0, 5, "Political Audio Fact-Checker", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)
        y = self.get_y() + 3
        self.line(10, y, 200, y)
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*GRAY)
        self.cell(0, 10, f"Page {self.page_no()}  |  Generated by Veritas", align="C")


def _label_value(pdf: FPDF, label: str, value: str):
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(45, 7, f"{label}:")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 7, _safe(value), new_x="LMARGIN", new_y="NEXT")


def _section_heading(pdf: FPDF, title: str):
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 9, title, new_x="LMARGIN", new_y="NEXT")
    y = pdf.get_y()
    pdf.set_draw_color(*DARK_RED)
    pdf.line(10, y, 200, y)
    pdf.set_draw_color(0, 0, 0)
    pdf.ln(3)


def _verdict_color(verdict: str):
    v = verdict.lower()
    if v == "verified":
        return GREEN
    if v == "false":
        return FALSE_RED
    if v == "misleading":
        return MISLEADING_ORANGE
    return GRAY


def generate_pdf(report_id: str, analysis: AnalysisResult) -> str:
    pdf = VeritasReport()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── metadata ─────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Analysis Report", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    for label, value in [
        ("Report ID", report_id),
        ("Analysis Date", analysis.analyzed_at),
        ("Model", analysis.model_used),
    ]:
        _label_value(pdf, label, value)
    pdf.ln(6)

    # ── verdict ───────────────────────────────────────────────────────
    _section_heading(pdf, "Verdict")

    score = analysis.overall_score
    is_consistent = score >= 60
    pdf.set_font("Helvetica", "B", 17)
    pdf.set_text_color(*(GREEN if is_consistent else FALSE_RED))
    pdf.cell(0, 11, _safe(analysis.verdict), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)

    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(*(GREEN if is_consistent else FALSE_RED))
    pdf.cell(0, 14, f"{score:.0f}%", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*GRAY)
    pdf.cell(0, 6, "Factual Consistency Score", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)

    # ── summary ───────────────────────────────────────────────────────
    fc = analysis.fact_check
    if fc and fc.summary:
        _section_heading(pdf, "Summary")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(190, 6, _safe(fc.summary))
        pdf.ln(6)

    # ── claims ────────────────────────────────────────────────────────
    if fc and fc.claims:
        _section_heading(pdf, "Fact-Check Results")
        for claim in fc.claims:
            color = _verdict_color(claim.verdict)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*color)
            pdf.set_x(pdf.l_margin)
            pdf.cell(0, 7, claim.verdict.upper(), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "I", 10)
            pdf.set_text_color(50, 50, 50)
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(190, 6, f'"{_safe(claim.claim)}"')
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(80, 80, 80)
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(190, 5, _safe(claim.explanation))
            if claim.sources:
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_text_color(*GRAY)
                pdf.set_x(pdf.l_margin)
                pdf.multi_cell(190, 5, "Sources: " + _safe(", ".join(claim.sources)))
            pdf.set_text_color(0, 0, 0)
            pdf.ln(4)

    # ── transcript ────────────────────────────────────────────────────
    if fc and fc.transcript:
        _section_heading(pdf, "Transcript")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(80, 80, 80)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(190, 5, _safe(fc.transcript))
        pdf.set_text_color(0, 0, 0)

    pdf_path = os.path.join(REPORTS_DIR, f"{report_id}.pdf")
    pdf.output(pdf_path)
    return pdf_path
